### ISSUE TITLE
Sort Glossary

### ISSUE THREAD

**Issue by pinguupinguu** [televandalist/RADocsTEMP#30]
Remove irrelevant terms, and find a better way to present it. Some form of table maybe with two columns "Term", "Definition". Right now, it's an eye-sore to read...

**Comment by televandalist** [comment]
> Remove irrelevant terms, and find a better way to present it. Some form of table maybe with two columns "Term", "Definition". Right now, it's an eye-sore to read...

The fact that it's mostly empty doesn't help.

**Comment by televandalist** [comment]
I got rid of all the dev terms since all that stuff is explained in the developer docs. I put each term in `code blocks` instead of each one having a header. Several terms still need to be defined, but "Sort Glossary" is done, I think.
